---
lang: fr
author:
  - name: Pierre J. FISCHER
    affiliation:
      - name: Pierre J. FISCHER
        department: fishrp@pm.me +33 76748 2009
        address: 39 rue de la Figairasse, Bat I
        postal-code: 34070
        city: MONTPELLIER
        country: F-
address:
  - FINESTRE
  - 539 rue Hélène Boucher
  - 34130 MAUGIO
subject: Suivi de panne sur volet roulant solaire
subject-title: "Objet"
subject-suffix: 
opening: "Cher Monsieur,"
closing: "Recevez mes plus sincères salutations,"
cc:
  - contact@finestre.fr et Mr Alvarez
encl: 
  - 01_FACTURE_4109_22092021
  - 02_PV_travaux_1781686998540
  - 03_signalement_defaut_apres_quatre_mois
  - 04_Garanties_Finestre
ps: 
format: letter-pdf
geometry: "left=4.0cm,right=2cm,bottom=2.2cm,top=1cm"
---

Je vous contacte en votre qualité de responsable légal de la société SARL Sud Menuiserie PVC - FINESTRE inscrit au RCS Montpellier 420 690 760 000 20, l'émetteur de la facture No 41/09 acquittée en date du 22/09/2021.

L'installation initiale est intervenue le 23-24 Septembre 2021 selon PV.

Quatre mois après l'installation, le dysfonctionnement initial de la télécommande est rapporté avec demande d'intervention.

Votre diligente intervention du 21 Juillet 2026 a réinitialisé le bon fonctionnement du volet SOM 21206201206.4.

*Désormais le volet SOM 21206201206.3 (dans la chambre adjacente) qui s'actionnait normalement, à partir du 23 Juillet 2026, montre à son tour le même symptôme que le numéro 4, à savoir aucune réponse du moteur, si ce n'est trois clignotements orange de la télécommande.*

Je vous prie donc de bien vouloir y remédier pareillement.
