---
title: "CONVENTION D'HONORAIRES"
format: letter-pdf
---

## ENTRE:

Monsieur Pierre FISCHER

Comme étant né le 08 février 1958 à LA WALCK,

Retraité,

Domicilié 39 rue de la Figairasse Bâtiment 1 34070 MONTPELLIER.

ci dessous dénommé le mandant

d'une part,

## ET

Maître Sophie FISCHER,

Demeurant 57 allée de la Robertsau à 67000 STRASBOURG

ci dessous dénommé le mandataire

d'autre part,

## IL EST EXPOSE

Le Mandant confie à Maître Sophie FISCHER, la défense de ses intérêts dans le cadre du dossier concernant une procédure de partage judiciaire à introduire dans la succession de feue sa Maman Madame Aline DURRENGERGER, décédée le 19 novembre 2021.

La présente convention se rapportant uniquement à la procédure ci-dessus précisée sans inclure les éventuels honoraires et frais d'exécution

Il est en conséquence établi entre les parties la présente convention d'honoraires.

<!-- Dans l'hypothèse où il serait alloué au mandant une indemnité aux titres des frais irrépétibles -->

<!-- supérieure au montant hors taxe des honoraires convenus, ce montant HT serait -->

<!-- automatiquement réévalué au montant de cette indemnité. -->

## HONORAIRE AU TEMPS PASSE

Il est expressément convenu que l'honoraire dû au titre du mandat qui lui a été confié est fixé sur une base horaire de 250 € HT soit 300 TTC, tarif en vigueur depuis 2017.

Maître Sophie FISCHER s'engage en conséquence à adresser au mandant des factures indiquant précisément les diligences accomplies et le temps passé.

<!--
## HONORAIRES DES AVOCATS CORRESPONDANTS

Le mandant reconnaît que les honoraires des Avocats correspondants intervenant pour son

compte à la demande de Maître Sophie FISCHER ne sont pas compris dans les honoraires dus à

cette dernière.

Le mandant s'engage à s'acquitter de leur facture sur présentation.
-->

## LES FRAIS

Il est expressément prévu entre les parties que les frais de Maître Sophie FISCHER seront à la charge du mandant sur justificatifs adressés.

A ce titre, le mandant règlera, sur présentation des factures les actes d'huissiers, et tous les débours nécessaires à la défense de ses intérêts.

Le mandant règlera à l'issue de la procédure, en sus des honoraires ci-dessus convenus, l'état des frais et dépens de Maître Sophie FISCHER, dont il n'aura pas fait l'avance

A ce titre les éventuels frais de déplacement seront facturés sur la base de 0,70 € HT du kilomètre auxquels s'ajouteront les éventuels frais de péage et parking.

## LA RUPTURE DE LA CONVENTION

Il est expressément prévu entre les parties qu'en cas de non -règlement par le mandant des honoraires mis à sa charge par la présente convention le mandataire sera déchargé de son mandat à condition d'avoir expressément notifié au mandant la rupture du contrat et cela par lettre recommandée avec avis d'accusé réception et moyennant le respect d'un préavis raisonnable pour préserver les droits du mandant.

## LE DESSAISISSEMENT

En cas de dessaisissement de Maître Sophie FISCHER, par le mandant, celui-ci sera tenu du règlement d'un honoraire au taux horaire de 250 € HT, TVA en sus, pour l'ensemble des diligences réalisées au jour du dessaisissement.

## CLAUSE DE MEDIATION

Le Client est informé de la possibilité qui lui est offerte par l'article L.152-1 du Code de la consommation, en cas de litige résultant de la présente convention, d'avoir recours au médiateur national de la profession d'Avocat à savoir :

Carole PASCAREL, médiateur de la consommation de la profession d'avocat
Adresse postale : 180 boulevard Haussmann, 75008 Paris
Adresse email : mediateur\@mediateur-consommation-avocat.fr
Site Internet : https://mediateur-consommation-avocat.fr

Le Client est informé que la saisine du médiateur ne peut intervenir qu'après avoir tenté au préalable de résoudre le litige directement auprès de l'Avocat par une réclamation écrite

## PROTECTION DES DONNEES A CARACTERE PERSONNEL

Les informations qui seront transmises à Maître Sophie FISCHER tout au long de la présente procédure peuvent constituer des données à caractère personnel relevant notamment de la vie privée de leurs clients.

Le cabinet a mis en œuvre le processus de protection des données personnelles de ses clients dans le respect des dispositions du RGPD entré en vigueur le 25 mai 2018, en application du règlement 2016/679 du parlement européen et du conseil du 27 avril 2016.

Le cabinet accord une importance toute particulière au respect du secret professionnel.
Le client accepte de transmettre à son avocat les données à caractère personnel nécessaires au traitement de son dossier, et l'autorise à les utiliser et les produire dans le cadre de la présente procédure.

Il s'engage à sécuriser les échanges de données entre lui et l'avocat mandaté dans leur transmission comme dans leur réception.

## CLAUSE DE DIFFICULTES

Tout litige relatif à l'exécution et/ou à l'interprétation et/ou à la résiliation de la présente convention relèvera de la seule compétence de Monsieur le Bâtonnier de l'Ordre des Avocats du Barreau de STRASBOURG.

## DELAI DE REFLEXION

Le Client reconnaît par la présente avoir bénéficié d'un délai suffisant pour apprécier l'étendue de ses obligations et de celles de son Avocat.

Fait à Montpellier, en triple exemplaire le




Le Mandant                                                  Maître Sophie FISCHER

(mention manuscrite Lu et Approuvé)
